services:
  backend:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./pretrained_models:/app/pretrained_models
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=${PORT:-8000}
      - HOST=0.0.0.0
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - UPLOAD_DIR=/app/uploads
      - TEMP_DIR=/app/temp
      - MODEL_PATH=/app/pretrained_models
    restart: unless-stopped

volumes:
  uploads:
  temp:
  pretrained_models:
